/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisoryRouteImport } from './routes/advisory'
import { Route as ControlsRouteImport } from './routes/controls'
import { Route as ScreeningRouteImport } from './routes/screening'
import { Route as ApiPublicSyncKnowledgeRouteImport } from './routes/api/public/sync-knowledge'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryRoute = AdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsRoute = ControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningRoute = ScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncKnowledgeRoute = ApiPublicSyncKnowledgeRouteImport.update({
  id: '/api/public/sync-knowledge',
  path: '/api/public/sync-knowledge',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisory': typeof AdvisoryRoute
  '/controls': typeof ControlsRoute
  '/screening': typeof ScreeningRoute
  '/api/public/sync-knowledge': typeof ApiPublicSyncKnowledgeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisory': typeof AdvisoryRoute
  '/controls': typeof ControlsRoute
  '/screening': typeof ScreeningRoute
  '/api/public/sync-knowledge': typeof ApiPublicSyncKnowledgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisory': typeof AdvisoryRoute
  '/controls': typeof ControlsRoute
  '/screening': typeof ScreeningRoute
  '/api/public/sync-knowledge': typeof ApiPublicSyncKnowledgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisory'
    | '/controls'
    | '/screening'
    | '/api/public/sync-knowledge'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisory'
    | '/controls'
    | '/screening'
    | '/api/public/sync-knowledge'
  id:
    | '__root__'
    | '/'
    | '/advisory'
    | '/controls'
    | '/screening'
    | '/api/public/sync-knowledge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisoryRoute: typeof AdvisoryRoute
  ControlsRoute: typeof ControlsRoute
  ScreeningRoute: typeof ScreeningRoute
  ApiPublicSyncKnowledgeRoute: typeof ApiPublicSyncKnowledgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory': {
      id: '/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls': {
      id: '/controls'
      path: '/controls'
      fullPath: '/controls'
      preLoaderRoute: typeof ControlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening': {
      id: '/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof ScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-knowledge': {
      id: '/api/public/sync-knowledge'
      path: '/api/public/sync-knowledge'
      fullPath: '/api/public/sync-knowledge'
      preLoaderRoute: typeof ApiPublicSyncKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisoryRoute: AdvisoryRoute,
  ControlsRoute: ControlsRoute,
  ScreeningRoute: ScreeningRoute,
  ApiPublicSyncKnowledgeRoute: ApiPublicSyncKnowledgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
